/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 cube.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cube(props) {
  const { nodes, materials } = useGLTF('/cube.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/cube.glb')
