/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cubeGrass.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Aset_nature_rock_XL_wldhdhxva_00_LOD1.geometry} material={materials.default_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/cubeGrass.glb')
